### ISSUE TITLE
columns: Add divider / alternating backgrounds option

### ISSUE THREAD

**Issue by luisgerhorst** [RRZE-Webteam/rrze-elements#186]
Otherwise it is very hard to distinguish the different columns. E.g. https://sys.cs.fau.de/lehre/ss22/sp1/uebung at the end of the page.

**Comment by cassandre** [comment]
In your example I would use a table.
For alterning backgrounds, you can use [alerts](https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/alerts-hinweisboxen/).

**Comment by luisgerhorst** [comment]
We are using a table. I do not see how alerts can be used to create alternating backgrounds in a table. Can you make an example showing how these could be combined in a meaningful way?

What would have to be done in order to get this feature planned?

**Comment by cassandre** [comment]
In the second half of the page (https://sys.cs.fau.de/lehre/ss22/sp1/uebung, sections Makefile, Übersetzerfehler, Fehlerbehandlung, Ausnahmen etc.) you are using columns where tables would be semantically correct AND be easier to edit AND solve the problem that the different columns are hard to distinguish.

The hint with the alerts was meant to provide columns with altering backgrounds: [column][alert] your text [/alert][/column].



Am 25.07.2022 um 13:06 schrieb Luis Gerhorst ***@***.******@***.***>>:



We are using a table. I do not see how alerts can be used to create alternating backgrounds in a table. Can you make an example showing how these could be combined in a meaningful way?

What would have to be done in order to get this feature planned?

**Comment by luisgerhorst** [comment]
I'm sorry I did not recall this correctly, I will try this later :)
